###########
# site.title, site.url, site.author.name

title:   '呵呵'
author:
  name:  'yu'

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)



########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

permalink: /:title.html

exclude:
- README.md


safe: true
lsi: false
mathjax: true

